version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gh2jira
    main: .
    binary: gh2jira
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: gh2jira
    builds:
      - gh2jira
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE
      - profiles.yaml
      - workflows.yaml

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
